### ISSUE TITLE
Thanks for your excellent work

### ISSUE THREAD

**Issue by lsgn12138** [oveilleux/Realistic_Transductive_Few_Shot#1]
Thank you for your excellent work.  
I also suffer performance degradation caused by class imbalance when implementing some classic work. At that time, I didn't think of any other methods except to stop using transductive methods. I want to solve the problem, but I don't have the ability. 
Your work has inspired me. Thank you very much.

**Comment by ibayed** [comment]
Happy to see this work is helping!
